# Generated by Django 4.0.3 on 2022-04-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allergen_options'),
        ('profiles', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.allergen', verbose_name='Аллергии'),
        ),
    ]
