# Generated by Django 4.0.3 on 2022-04-19 20:23

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', profiles.models.CustomUserManager()),
            ],
        ),
    ]
