# Generated by Django 4.0.3 on 2022-04-03 21:27

import articles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.IntegerField(choices=[(1, 'Новость'), (2, 'Плитки на главной')], default=1, verbose_name='Тип')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=articles.models.article_cover_upload_path, verbose_name='Обложка')),
                ('show_cover', models.BooleanField(default=False, verbose_name='Показывать обложку в статье')),
                ('creation_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['article_type', 'published', 'creation_dt'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Подзаголовок'), (3, 'Картинка'), (4, 'Карусель'), (5, 'Видео')], verbose_name='Тип блока')),
                ('position', models.SmallIntegerField(verbose_name='Порядок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('text_styles', models.TextField(blank=True, verbose_name='Стили текста')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрытый')),
                ('add_hr', models.BooleanField(default=False, verbose_name='Разделитель под блоком')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новостей',
                'ordering': ['article', 'position'],
            },
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='Название')),
                ('image', models.ImageField(upload_to=articles.models.block_image_upload_path, verbose_name='Картинка')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('block', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.articleblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Картинка новости',
                'verbose_name_plural': 'Картинки новостей',
                'ordering': ['block', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='blockimage',
            index=models.Index(fields=['block'], name='articles_bl_block_i_152480_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockimage',
            unique_together={('block', 'position')},
        ),
        migrations.AddIndex(
            model_name='articleblock',
            index=models.Index(fields=['article'], name='articles_ar_article_372289_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleblock',
            unique_together={('article', 'position')},
        ),
    ]
