# Generated by Django 4.0.3 on 2022-04-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblock',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_blocks', to='articles.articleblock', verbose_name='Родительский блок'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='horizontal',
            field=models.BooleanField(default=True, verbose_name='Блоки внутри горизонтально'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='block_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Подзаголовок'), (3, 'Картинка'), (4, 'Карусель'), (5, 'Видео'), (6, 'Контейнер для блоков')], verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='text_styles',
            field=models.TextField(blank=True, verbose_name='Стили'),
        ),
    ]
