# Generated by Django 4.0.3 on 2022-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleblock_container_articleblock_horizontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, 'Новость'), (2, 'Плитки на главной'), (3, 'Проект')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='horizontal',
            field=models.BooleanField(default=False, verbose_name='Блоки внутри горизонтально'),
        ),
        migrations.AddIndex(
            model_name='articleblock',
            index=models.Index(fields=['container'], name='articles_ar_contain_f999a0_idx'),
        ),
    ]
