# Generated by Django 4.0.3 on 2022-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, 'Новость'), (2, 'Плитки на главной'), (3, 'Проект'), (4, 'Описание аллергена')], default=1, verbose_name='Тип'),
        ),
    ]
