# Generated by Django 4.0.3 on 2022-04-03 21:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('latin_title', models.CharField(max_length=100, verbose_name='Латинское название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('short_description', models.TextField(verbose_name='Короткое описание')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиция')),
                ('image', models.ImageField(upload_to=main.models.instance_id_upload_path, verbose_name='Круг')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ['position'],
            },
        ),
    ]
