# Generated by Django 4.0.3 on 2022-04-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['title'], 'verbose_name': 'Аллерген', 'verbose_name_plural': 'Аллергены'},
        ),
    ]
