# Generated by Django 4.0.3 on 2022-04-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allergen_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='high',
            field=models.PositiveIntegerField(default=0, verbose_name='Высокий риск'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='low',
            field=models.PositiveIntegerField(default=0, verbose_name='Низкий риск'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='middle',
            field=models.PositiveIntegerField(default=0, verbose_name='Средний риск'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='unit',
            field=models.CharField(default='м<sup><small>3</small></sup>', max_length=60, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='allergen',
            name='very_high',
            field=models.PositiveIntegerField(default=0, verbose_name='Очень высокий риск'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PollenCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('concentration', models.FloatField(verbose_name='Концентрация')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.allergen', verbose_name='Аллерген')),
            ],
            options={
                'verbose_name': 'Пыление',
                'verbose_name_plural': 'Календарь пылений',
                'ordering': ['date', 'allergen'],
            },
        ),
        migrations.AddIndex(
            model_name='pollencalendar',
            index=models.Index(fields=['date', 'allergen'], name='main_pollen_date_fcae02_idx'),
        ),
        migrations.AddIndex(
            model_name='pollencalendar',
            index=models.Index(fields=['allergen'], name='main_pollen_allerge_43b1f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollencalendar',
            unique_together={('date', 'allergen')},
        ),
    ]
