# Generated by Django 4.0.3 on 2022-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_allergen_high_allergen_low_allergen_middle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='allergen_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пыльца растений'), (2, 'Споры грибов')], default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='multiplier',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Вес (множитель)'),
        ),
    ]
