# Generated by Django 4.0.3 on 2022-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_allergen_allergen_type_allergen_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['allergen_type', 'title'], 'verbose_name': 'Аллерген', 'verbose_name_plural': 'Аллергены'},
        ),
        migrations.AlterField(
            model_name='allergen',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
