# Generated by Django 4.0.3 on 2022-04-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_allergen_options_alter_allergen_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollencalendar',
            options={'ordering': ['date', 'allergen'], 'verbose_name': 'Запись о пылении', 'verbose_name_plural': 'Календарь пылений'},
        ),
    ]
