# Generated by Django 4.0.3 on 2022-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pollencalendar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollencalendar',
            options={'ordering': ['-date', 'allergen'], 'verbose_name': 'Запись о пылении', 'verbose_name_plural': 'Календарь пылений'},
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='unit',
        ),
    ]
