# Generated by Django 4.0.3 on 2022-05-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_article_type'),
        ('main', '0008_remove_allergen_description_allergen_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['title'], 'verbose_name': 'Аллерген', 'verbose_name_plural': 'Аллергены'},
        ),
        migrations.AlterField(
            model_name='allergen',
            name='about',
            field=models.ForeignKey(blank=True, limit_choices_to={'article_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergen', to='articles.article', verbose_name=''),
        ),
    ]
