# Generated by Django 4.0.3 on 2022-05-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_article_type'),
        ('main', '0009_alter_allergen_options_alter_allergen_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='about',
            field=models.OneToOneField(blank=True, limit_choices_to={'article_type': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergen', to='articles.article', verbose_name=''),
        ),
    ]
